### PR TITLE
Fixes edge case at chunk boundaries.

### PR DESCRIPTION
**Pull request by plusplusben**
I created a failing test for this. It passes now. There's probably a way to fix this without the needmore flag, but that was all I could think of. Feel free to change it around.

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Thanks @plusplusben  - can you please take a look at the tests failing and debug?

Also please note that currently we do not use ES6 in this repo, as it is intended to be a drop-in replacement for https://github.com/EvanOxfeld/node-unzip which works for old versions of node as well as the more recent ones.

**Comment by plusplusben** [comment]
Oh, yeah I'll fix the ES6 thing. I typically only write in ES6 these days, so I guess it's just habit now. Hopefully that will fix the test.

**Comment by plusplusben** [comment]
I removed the ES6, and that fixed some of the tests, but I'm still not sure why this is failing in older versions of Node. One of the failures doesn't even seem related to my test or changes.

**Comment by ZJONSSON** [comment]
Can you rebase and see if tests are passing now?

**Comment by plusplusben** [comment]
Well, I tried again, but it's still having problems with Node 0.10. I'm not sure what's up. There may be some issues with my fix. I'm pretty sure my test is pretty good though.

**Comment by ZJONSSON** [comment]
Hey @plusplusben  so I have found a fix, but it relies on some internal stream magic I think.  If I add the condition that `!this.__ended` in front of the write all tests pass:

https://github.com/ZJONSSON/node-unzipper/blob/603848613db46674e25ce95d171a2abf8e5c500f/lib/PullStream.js#L63-L64


Here are the green tests: https://travis-ci.org/ZJONSSON/node-unzipper/builds/468836305

Can you please take a look and see if this looks like a safe fix?  If so please add to your PR so we can get this in.

**Comment by plusplusben** [comment]
Ok, all tests are passing, so I think this is good to go.

**Comment by ZJONSSON** [comment]
Awesome, thanks again @plusplusben  - squashed and merged
Published as: `+ unzipper@0.9.6`

**Comment by plusplusben** [comment]
I hate to be the bearer of bad news, but with this new version, with the !this.__ended check, it's causing some of my unzips to pause again. This might have some unintended consequences. I would suggest unpublishing until we know what's going on.

**Comment by ZJONSSON** [comment]
Thanks @plusplusben much appreciated.   I'm tempted to go back to your original implementation without the `(!this.__ended)`, particularly if the node 0.1 would fail anyway on odd chunks so this change would not make the behavior worse.   In that case we might just disable the chunkBoundary test for node 0.1?

See here as test fails testChunkBoundary without your fix anyway on previous master https://travis-ci.org/ZJONSSON/node-unzipper/jobs/469772521

**Pull request merged**
