### PR TITLE
Crx

### PR DESCRIPTION
**Pull request by ZJONSSON**
Closes https://github.com/ZJONSSON/node-unzipper/issues/118
Add support for crx files in methods `Parse()` `ParseOne()` and `Open.buffer()`

### CODE REVIEW

**Comment by silverwind** [comment]
Some suggestions:

1. Make `crxHeader` available on the result of `Open`, e.g. `directory.crxHeader`.
2. Any specific reason to not support it on `Open` methods other than `buffer`? While I'm happy with it in my current use case, I think the buffer slicing could be extracted to its own function and made available on all `Open` methods.

**Comment by ZJONSSON** [comment]
1) good point - will do
2) it will require an extra roundtrip to the server to inspect the header of the file.  A regular zip file would not require inspecting the header.   We could have an optional `findStartOffset: true` that would trigger header inspection that searches for start of the zip file and add the startOffset to any offset references in the dictionary

**Comment by silverwind** [comment]
Ah, I see. For methods that fetch a remote file, it's probably not worth the overhead. For `Open.file` it may be, but I guess we could also just leave it unsupported there given that reading a file (or parts of it) into a buffer is trivial.

**Comment by ZJONSSON** [comment]
I'm thinking we should add the crx option to all method before merging.  I have a first cut, will try to finish soon

**Comment by silverwind** [comment]
👍 probably best to do it on all methods via opt-in.

**Comment by ZJONSSON** [comment]
@silverwind this is now complete, can you please review

**Comment by silverwind** [comment]
Sorry for being so late here. Looks fine to me, thanks again!

**Pull request merged**
