### PR TITLE
Fix: Unix OS's should properly ignore the windows zip slipped files

### PR DESCRIPTION
**Pull request by Glen-Nicol-Garmin**
Code and test case for:
https://github.com/ZJONSSON/node-unzipper/pull/59#issuecomment-584337920

I ran this on the standard node docker image(linux) to verify change in behavior.

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Thanks @Glen-Nicol-Garmin, very nice!!   Can you do me a favor and leave the original zip-slip test exactly as it was before,  and add this as a separate test?

**Comment by Glen-Nicol-Garmin** [comment]
Done.

**Comment by Glen-Nicol-Garmin** [comment]
@ZJONSSON Can this be merged now?

**Comment by vincent-seibus** [comment]
Hello,
I have got the issue when extracting a windows zip on linux debian machine, this pull request solves the problem (i tried it). Can you merge this to a new version ?
Thanks very much !

**Comment by ZJONSSON** [comment]
Thanks @Glen-Nicol-Garmin

**Pull request merged**
