### PR TITLE
Normalize Extract path before using it

### PR DESCRIPTION
**Pull request by MRayermannMSFT**

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Awesome, thanks @MRayermannMSFT  
Would it be easy for you to add a test that would fail without this fix?

**Comment by MRayermannMSFT** [comment]
Sure, give me a few hours.

**Comment by ZJONSSON** [comment]
Thanks that would be great,  I'l gonna merge and publish right now to ensure the fix is in.  If you can add the test later that would be very helpful.

**Comment by ZJONSSON** [comment]
published as `+ unzipper@0.9.13`

**Pull request merged**
