### PR TITLE
Fix multiple tests under Windows

### PR DESCRIPTION
**Pull request by vitalyster**
chunkBoundary test is still failing (sometimes it works), I'm not sure how to fix it

### CODE REVIEW

**Comment by vitalyster** [comment]
[Passed](https://ci.appveyor.com/api/buildjobs/k90q5k4wpa9phj5j/log) on first run
[Failed](https://ci.appveyor.com/api/buildjobs/c0pggt1jv89yhfpb/log) on second run :/

**Comment by ZJONSSON** [comment]
Thanks again @vitalyster - I think I have fixed the multiple callbacks error [here](https://github.com/ZJONSSON/node-unzipper/pull/100)
The fix has been merged to master, so if you rebase this PR we should be good to merge this in (I double checked on a windows VM, but can you please verify)

**Comment by vitalyster** [comment]
That's strange but not it does not find tests at all - https://ci.appveyor.com/api/buildjobs/44m72c0ejayb2atx/log

**Comment by vitalyster** [comment]
With latest commit it works - https://ci.appveyor.com/api/buildjobs/42ytypwo6b69kxjm/log

**Comment by ZJONSSON** [comment]
Awesome, thanks @vitalyster!

**Pull request merged**
