### PR TITLE
Refactored to catchable error handling

### PR DESCRIPTION
**Pull request by timt-unity3d**
I'm trying to validate that the zip files in S3 are actually valid. The error handling on bad zip files was completely killing my node process. This allows the promise returned by Open to catch the FILE_ENDED error. This may not be the best way to do it.

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Thanks @timt-unity3d.   Error handling between streams and promises can get a little tricky.    I can not accept the PR as-is, as it's not ideal to squash errors into console.logs by default - preventing the ability to properly capture them.  Errors "should " propagate properly into the respective error handlers outside of the library (`catch(console.log)` for promises returned and `.on('error',console.log)` for streams.   If in your case the errors did not propagate then we need to figure out the ideal fix.   I will try to replicate the issue - did the process crash as you were getting the directory, or after you started streaming a file?

This PR might have something to do with this: https://github.com/ZJONSSON/node-unzipper/pull/27/files

Can check if this issue is also seen in the next release candidate? `unzipper@r0.9.0-rc8`  (https://github.com/ZJONSSON/node-unzipper/tree/combine-api)

Thanks again

**Comment by timt-unity3d** [comment]
Hi @ZJONSSON thanks for looking into this so fast. I am indeed using the latest release candidate branch (combine-api). The test case is pretty simple. I took a README file, renamed it to bad.zip and uploaded it to S3. It's blowing up in reading the S3 directory. My code looks like this:

```
    await unzipper.Open.s3(s3Client, {Bucket: bucket, Key: key})
            .then((directory) => {
                 console.log('read directory');
            }).catch((e) => {
                 console.error('caught it properly', e);
            });
```

Without my changes it would fail with an uncaught exception error outside the catch. This newest PR seems to work, and the error is caught in the PR.

**Comment by timt-unity3d** [comment]
This needs rework with latest code. I'm going to close and reassess.

**Comment by ZJONSSON** [comment]
Thank you @timt-unity3d let me know if there is anything I can do!

**Pull request closed without merging**
