### PR TITLE
Fix for #47

### LINKED ISSUE #47: [QUESTION] Handling of directory entries
Hi,

Quick query around the parsing of directory entries...

When checking if an entry is a `File` or `Directory` the following check is used:

[`entry.type = (vars.compressedSize === 0 && /[\/\\]$/.test(fileName)) ? 'Directory' : 'File';`](https://github.com/ZJONSSON/node-unzipper/blob/1bc85fa/lib/parse.js#L96)

Should this use `vars.uncompressedSize` instead of `vars.compressedSize`? I only ask as I'm getting a directory being typed as a file in [this archive](https://github.com/ZJONSSON/node-unzipper/files/1292053/Jk5ER6CRSVi32R_ZHeuAyg.zip)!

(You can tell its being typed as a file as the [`inflating:` prefix is used for files](https://github.com/ZJONSSON/node-unzipper/blob/1bc85fa/lib/parse.js#L105))
```
  inflating: META-INF/
{ filename: 'META-INF/',
  vars: 
   { versionsNeededToExtract: 20,
     flags: 2048,
     compressionMethod: 8,
     lastModifiedTime: 42365,
     lastModifiedDate: 19241,
     crc32: 0,
     compressedSize: 2,
     uncompressedSize: 0,
     fileNameLength: 9,
     extraFieldLength: 0 },
  extra: 
   { signature: null,
     partsize: null,
     uncompressedSize: null,
     compressedSize: null,
     offset: null,
     disknum: null } }
```

I note in this `vars` that the uncompressed size is 0 (while the compressed size is 2), hence my query!

Also running `zipinfo Jk5ER6CRSVi32R_ZHeuAyg.epub | grep META-INF/`

```
?rwxr-xr-x  2.0 unx        0 b- defN 17-Sep-09 20:43 META-INF/
?rw-------  2.0 unx      244 b- defN 17-Sep-09 20:43 META-INF/container.xml
```

Cheers!

### PR DESCRIPTION
**Pull request by rhodgkins**
Fixed #47 

Sorry about the size of the test file - I couldn't find anything smaller.

### CODE REVIEW

**Comment by ZJONSSON** [comment]
The fix looks good - however the test file looks very bloated and does not include licensing information and I'm not sure I can republish.  Can you create a zip file from scratch that fails previously but works after this change?

**Comment by rhodgkins** [comment]
@ZJONSSON yeh sorry about that. I'm not sure how to go about creating a ZIP file like this, but I found an [online tool](https://ebook.online-convert.com/convert-to-epub) which produces these files. Would you be ok with me creating a blank one of these?

**Comment by ZJONSSON** [comment]
Absolutely - ideally the file should "fail" before your fix and work after the fix

**Comment by rhodgkins** [comment]
Yeh I'm not sure why it passed my failing tests - I'm not sure if its because the CI tests are on a different platform to my local attempts at testing. I'll update this PR later with the new file and try again.

**Comment by rhodgkins** [comment]
@ZJONSSON I've updated from maser and changed to a smaller test file - all yours!

**Comment by ZJONSSON** [comment]
Looks great, thanks!!

**Comment by ZJONSSON** [comment]
published `+ unzipper@0.8.12`

**Pull request merged**
