### PR TITLE
replace bigint with node-int64

### PR DESCRIPTION
**Pull request by lechuhuuha**
This is an attempt to add support for [broofa/node-int64](https://www.npmjs.com/package/node-int64). 

Summary from [this reply](https://github.com/ZJONSSON/node-unzipper/issues/38#issuecomment-699529036):

- Use node-int64 instead of big-integer
- After that performance was increased x20 for large files. (11mb - ~9sec).

If merged, this PR should resolve https://github.com/ZJONSSON/node-unzipper/issues/38 and https://github.com/ZJONSSON/node-unzipper/issues/224

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Thanks, @lechuhuuha. Can you clean this PR up (remove the extra newlines) and also remove `big-integer` from package.json if it's no longer required?

**Comment by lechuhuuha** [comment]
Yes i will do that
Thanks for point its out

**Comment by lechuhuuha** [comment]
I had editted the PR 
You can check it out @ZJONSSON.

Thanks

**Comment by ZJONSSON** [comment]
Thanks @lechuhuuha!

**Pull request merged**
