### PR TITLE
Filename encodings support

### PR DESCRIPTION
**Pull request by vitalyster**
When 0x11 general purpose bit is not set then filenames are stored in IBM PC (or Windows OEM encoding) but not in UTF-8. Not all ZIPs are follow ZIP spec but at least we can force desired encoding

### CODE REVIEW

**Comment by ZJONSSON** [comment]
Thanks I did not know this, really appreciate the PR.   Should we make the default encoding Windows OEM encoding if the bit is not set (i.e. default behavior should match what you said above?)

Also could you add tests for the `Open/directory` and `Open/unzip`?

**Comment by vitalyster** [comment]
1) We can not reliable detect which encoding was used when zip was created: in Windows we can get current OEM encoding with `GetConsoleCP` Win32 API call, but it will match zip filename encoding only when zip was created on the same machine
2) many zip tools (especially under mac, linux) incorrectly use UTF-8 without setting this encoding bit

**Comment by ZJONSSON** [comment]
Thanks this clears it up.  Your implementation here makes perfect sense. 

Can you update the README to include instructions and clarification on windows encoding?

Also I think we need to add `options` as an additional parameter in all the `Open` methods [here](https://github.com/ZJONSSON/node-unzipper/blob/master/lib/Open/index.js) and pass it on to the `return directory(source, options)`

Also we need test coverage to cover the open methods (at least one of them)

When we merge this in we need to do a PR to the type definitions to include `options` argument https://github.com/DefinitelyTyped/DefinitelyTyped/blob/adf98fa85cb7b7c5bad10d31292cc5876b3c3176/types/unzipper/index.d.ts

**Comment by vitalyster** [comment]
@ZJONSSON please merge https://github.com/ZJONSSON/node-unzipper/pull/96 so I can update tests for Open methods

**Comment by vitalyster** [comment]
I have no experience with type definitions, can you help with that?

**Comment by vitalyster** [comment]
@ZJONSSON please review

**Comment by ZJONSSON** [comment]
Brilliant!!! Thanks @vitalyster

**Comment by ZJONSSON** [comment]
published as `+ unzipper@0.9.10`

**Pull request merged**
